name: test_and_deploy_docs
on:
  push:
    branches:
      - main
jobs:
  test_and_deploy:
    name: test_and_deploy
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install Dependencies
        run: bun install
      - name: Build
        run: bun run build
      - name: Build TypeDoc
        run: bun run docs
        working-directory: apps/docs
      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/docs/build/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
